import { Trade, Session, Strategy } from '../store/useStore';

// ============================================
// COMPREHENSIVE SEED DATA
// Realistic trading data to showcase all features
// 30+ trades across different strategies, sessions, and outcomes
// ============================================

export const fakeTrades: Trade[] = [
    // ========== WEEK 1: Strong Start ==========
    {
        id: '1',
        date: '2024-02-05',
        time: '09:30',
        symbol: 'EURUSD',
        type: 'buy',
        entry: 1.08542,
        exit: 1.09210,
        sl: 1.08200,
        tp: 1.09500,
        lotSize: 0.5,
        riskPercent: 1.2,
        rrPlanned: 3.2,
        rrActual: 2.8,
        pipsProfit: 67,
        profit: 335,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Perfect ICT Silver Bullet setup. Clean FVG at 9:30 NY open. Followed plan exactly. Entry on 1min OB, SL below previous low. Target hit within 30 minutes.',
        emotionBefore: 'Focused',
        emotionAfter: 'Satisfied',
        mistakes: [],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: ['Wait for FVG', '9:30 NY Open', '1:3 RR minimum', 'Asian range breakout']
    },
    {
        id: '2',
        date: '2024-02-05',
        time: '14:45',
        symbol: 'GBPUSD',
        type: 'buy',
        entry: 1.26450,
        exit: 1.26820,
        sl: 1.26200,
        tp: 1.27200,
        lotSize: 0.3,
        riskPercent: 1.0,
        rrPlanned: 2.5,
        rrActual: 1.8,
        pipsProfit: 37,
        profit: 111,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'London continuation trade. Price broke above Asian range, retested as support. Entered on 5min bullish engulfing. Took partials at 1:1, BE at 1:2. Full TP hit.',
        emotionBefore: 'Confident',
        emotionAfter: 'Disciplined',
        mistakes: [],
        strategy: 'London Breakout',
        session: 'London',
        rulesUsed: ['Asian range breakout', 'Wait for retest', '5min confirmation']
    },
    {
        id: '3',
        date: '2024-02-06',
        time: '08:15',
        symbol: 'XAUUSD',
        type: 'sell',
        entry: 2035.80,
        exit: 2028.50,
        sl: 2039.00,
        tp: 2020.00,
        lotSize: 0.2,
        riskPercent: 1.5,
        rrPlanned: 2.8,
        rrActual: 2.1,
        pipsProfit: 73,
        profit: 146,
        status: 'TP',
        assetCategory: 'Commodities',
        notes: 'Gold rejected from daily supply zone. Clear bearish order block on 15min. Bearish divergence on RSI. Short entry on bearish engulfing.',
        emotionBefore: 'Patient',
        emotionAfter: 'Neutral',
        mistakes: [],
        strategy: 'Supply & Demand',
        session: 'London',
        rulesUsed: ['Daily zone confluence', '15min OB', 'RSI divergence']
    },
    
    // ========== WEEK 2: Mixed Results, Learning ==========
    {
        id: '4',
        date: '2024-02-08',
        time: '02:30',
        symbol: 'BTCUSD',
        type: 'buy',
        entry: 42100,
        exit: 41800,
        sl: 41800,
        tp: 45000,
        lotSize: 0.1,
        riskPercent: 2.0,
        rrPlanned: 4.5,
        rrActual: 0,
        pipsProfit: -300,
        profit: -300,
        status: 'SL',
        assetCategory: 'Crypto',
        notes: 'BREAKING RULES: Took this trade out of boredom at 2:30 AM. No clear setup, just hoping for a bounce. Should have gone to sleep. Lack of discipline.',
        emotionBefore: 'Bored',
        emotionAfter: 'Regretful',
        mistakes: ['Late Entry', 'No Setup', 'Revenge Trading', 'Overtrading'],
        strategy: 'Unspecified',
        session: 'Asian',
        rulesUsed: []
    },
    {
        id: '5',
        date: '2024-02-08',
        time: '09:30',
        symbol: 'EURUSD',
        type: 'sell',
        entry: 1.07850,
        exit: 1.07850,
        sl: 1.08050,
        tp: 1.07200,
        lotSize: 0.4,
        riskPercent: 1.0,
        rrPlanned: 3.2,
        rrActual: 0,
        pipsProfit: 0,
        profit: 0,
        status: 'BE',
        assetCategory: 'Forex',
        notes: 'Silver Bullet setup but moved SL to BE too early after 5 pips profit. Price eventually hit original TP. FEAR - letting winners run. Need to trust the process.',
        emotionBefore: 'Anxious',
        emotionAfter: 'Frustrated',
        mistakes: ['Early Exit', 'Fear'],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: ['9:30 NY Open', 'FVG entry']
    },
    {
        id: '6',
        date: '2024-02-09',
        time: '10:15',
        symbol: 'NAS100',
        type: 'buy',
        entry: 17520,
        exit: 17680,
        sl: 17450,
        tp: 17800,
        lotSize: 0.3,
        riskPercent: 1.5,
        rrPlanned: 2.5,
        rrActual: 2.3,
        pipsProfit: 160,
        profit: 480,
        status: 'TP',
        assetCategory: 'Indices',
        notes: 'Tech stocks bouncing from support. Clean demand zone on 1H. 15min bullish engulfing confirmation. Strong risk:reward. Followed plan perfectly.',
        emotionBefore: 'Focused',
        emotionAfter: 'Confident',
        mistakes: [],
        strategy: 'Supply & Demand',
        session: 'New York',
        rulesUsed: ['1H zone', '15min confirmation', '1:2.5 RR']
    },
    {
        id: '7',
        date: '2024-02-09',
        time: '14:20',
        symbol: 'US30',
        type: 'sell',
        entry: 38650,
        exit: 38580,
        sl: 38800,
        tp: 38200,
        lotSize: 0.2,
        riskPercent: 1.8,
        rrPlanned: 2.1,
        rrActual: 0.6,
        pipsProfit: -70,
        profit: -140,
        status: 'SL',
        assetCategory: 'Indices',
        notes: 'Counter-trend trade. Dow was bullish all day but I tried to pick a top. Bad decision - should trade with trend. FOMO on the short side.',
        emotionBefore: 'FOMO',
        emotionAfter: 'Disappointed',
        mistakes: ['Counter Trend', 'FOMO'],
        strategy: 'EMA Crossover',
        session: 'New York',
        rulesUsed: []
    },
    
    // ========== WEEK 3: Discipline Issues ==========
    {
        id: '8',
        date: '2024-02-12',
        time: '03:00',
        symbol: 'EURUSD',
        type: 'buy',
        entry: 1.08200,
        exit: 1.08150,
        sl: 0,
        tp: 0,
        lotSize: 1.0,
        riskPercent: 5.0,
        rrPlanned: 0,
        rrActual: 0,
        pipsProfit: -5,
        profit: -500,
        status: 'open',
        assetCategory: 'Forex',
        notes: 'CRITICAL MISTAKE: No stop loss! Oversized position (5% risk). Panic closed after small move against me. Revenge trading after yesterday\'s loss. Very emotional.',
        emotionBefore: 'Revengeful',
        emotionAfter: 'Ashamed',
        mistakes: ['No SL', 'Oversized Position', 'Revenge Trading', 'Emotional Trading'],
        strategy: 'Unspecified',
        session: 'Asian',
        rulesUsed: []
    },
    {
        id: '9',
        date: '2024-02-12',
        time: '09:45',
        symbol: 'GBPUSD',
        type: 'buy',
        entry: 1.26800,
        exit: 1.27400,
        sl: 1.26500,
        tp: 1.28000,
        lotSize: 0.4,
        riskPercent: 1.2,
        rrPlanned: 2.8,
        rrActual: 2.0,
        pipsProfit: 60,
        profit: 240,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Back to basics. Clean London session breakout. Waited for proper setup, followed risk management. Good recovery mentally. One loss doesn\'t define me.',
        emotionBefore: 'Cautious',
        emotionAfter: 'Relieved',
        mistakes: [],
        strategy: 'London Breakout',
        session: 'London',
        rulesUsed: ['Proper setup', 'Correct sizing', 'Defined SL']
    },
    {
        id: '10',
        date: '2024-02-13',
        time: '11:30',
        symbol: 'XAUUSD',
        type: 'sell',
        entry: 2015.00,
        exit: 2015.00,
        sl: 2025.00,
        tp: 1980.00,
        lotSize: 0.3,
        riskPercent: 1.0,
        rrPlanned: 3.5,
        rrActual: 0,
        pipsProfit: 0,
        profit: 0,
        status: 'BE',
        assetCategory: 'Commodities',
        notes: 'Overnight position. Moved SL to BE before bed. Woke up to find gold tanked 50 pips past my TP. Fear of giving back profits.',
        emotionBefore: 'Anxious',
        emotionAfter: 'Regretful',
        mistakes: ['Early Exit'],
        strategy: 'Supply & Demand',
        session: 'New York',
        rulesUsed: ['Daily supply zone']
    },
    {
        id: '11',
        date: '2024-02-13',
        time: '15:45',
        symbol: 'EURUSD',
        type: 'buy',
        entry: 1.08000,
        exit: 1.07850,
        sl: 1.07800,
        tp: 1.08500,
        lotSize: 0.5,
        riskPercent: 1.5,
        rrPlanned: 2.3,
        rrActual: -0.5,
        pipsProfit: -15,
        profit: -75,
        status: 'SL',
        assetCategory: 'Forex',
        notes: 'Chopped up in ranging market. Should have stayed out. No clear trend, forced a trade. Overtrading today - 3rd trade.',
        emotionBefore: 'Impatient',
        emotionAfter: 'Tired',
        mistakes: ['Overtrading', 'No Trend'],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: []
    },
    
    // ========== WEEK 4: Recovery & Growth ==========
    {
        id: '12',
        date: '2024-02-15',
        time: '09:30',
        symbol: 'EURUSD',
        type: 'sell',
        entry: 1.07750,
        exit: 1.07200,
        sl: 1.08000,
        tp: 1.06800,
        lotSize: 0.5,
        riskPercent: 1.0,
        rrPlanned: 3.0,
        rrActual: 2.8,
        pipsProfit: 55,
        profit: 275,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Excellent Silver Bullet. Strong bearish momentum. Clean FVG entry. Let winner run to full TP. Perfect execution.',
        emotionBefore: 'Focused',
        emotionAfter: 'Proud',
        mistakes: [],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: ['FVG entry', 'Momentum confirmation', 'Full TP']
    },
    {
        id: '13',
        date: '2024-02-16',
        time: '08:00',
        symbol: 'GBPUSD',
        type: 'buy',
        entry: 1.26500,
        exit: 1.27000,
        sl: 1.26200,
        tp: 1.27500,
        lotSize: 0.4,
        riskPercent: 1.2,
        rrPlanned: 2.5,
        rrActual: 2.5,
        pipsProfit: 50,
        profit: 200,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'London session strength. Bounced from 1H demand. Bullish engulfing on 15min. Textbook setup.',
        emotionBefore: 'Disciplined',
        emotionAfter: 'Satisfied',
        mistakes: [],
        strategy: 'London Breakout',
        session: 'London',
        rulesUsed: ['1H demand', '15min engulfing']
    },
    {
        id: '14',
        date: '2024-02-16',
        time: '19:30',
        symbol: 'BTCUSD',
        type: 'buy',
        entry: 51200,
        exit: 52500,
        sl: 50500,
        tp: 54000,
        lotSize: 0.1,
        riskPercent: 1.5,
        rrPlanned: 2.8,
        rrActual: 2.1,
        pipsProfit: 1300,
        profit: 130,
        status: 'open',
        assetCategory: 'Crypto',
        notes: 'Crypto swing trade. Strong support at 50k. Bullish divergence. Taking partials as it moves up. Still holding position.',
        emotionBefore: 'Patient',
        emotionAfter: 'Optimistic',
        mistakes: [],
        strategy: 'Crypto Swing',
        session: 'New York',
        rulesUsed: ['Support hold', 'Divergence', 'Swing rules']
    },
    {
        id: '15',
        date: '2024-02-19',
        time: '09:30',
        symbol: 'NAS100',
        type: 'buy',
        entry: 17700,
        exit: 17850,
        sl: 17600,
        tp: 18000,
        lotSize: 0.3,
        riskPercent: 1.0,
        rrPlanned: 2.5,
        rrActual: 1.8,
        pipsProfit: 150,
        profit: 450,
        status: 'TP',
        assetCategory: 'Indices',
        notes: 'Tech earnings beat expectations. Gap up, pullback to previous resistance turned support. Strong demand zone.',
        emotionBefore: 'Confident',
        emotionAfter: 'Happy',
        mistakes: [],
        strategy: 'Supply & Demand',
        session: 'New York',
        rulesUsed: ['Earnings momentum', 'Support flip', 'Gap pullback']
    },
    
    // ========== WEEK 5: Overtrading Pattern ==========
    {
        id: '16',
        date: '2024-02-20',
        time: '08:15',
        symbol: 'EURUSD',
        type: 'buy',
        entry: 1.08200,
        exit: 1.08350,
        sl: 1.08050,
        tp: 1.08600,
        lotSize: 0.3,
        riskPercent: 1.0,
        rrPlanned: 2.0,
        rrActual: 1.5,
        pipsProfit: 15,
        profit: 45,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Small win. London scalping.',
        emotionBefore: 'Neutral',
        emotionAfter: 'Neutral',
        mistakes: [],
        strategy: 'Scalping',
        session: 'London',
        rulesUsed: []
    },
    {
        id: '17',
        date: '2024-02-20',
        time: '10:30',
        symbol: 'EURUSD',
        type: 'sell',
        entry: 1.08380,
        exit: 1.08280,
        sl: 1.08500,
        tp: 1.08000,
        lotSize: 0.3,
        riskPercent: 1.0,
        rrPlanned: 2.1,
        rrActual: 1.0,
        pipsProfit: 10,
        profit: 30,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Quick scalp. Moving average bounce.',
        emotionBefore: 'Focused',
        emotionAfter: 'Okay',
        mistakes: [],
        strategy: 'Scalping',
        session: 'London',
        rulesUsed: []
    },
    {
        id: '18',
        date: '2024-02-20',
        time: '13:45',
        symbol: 'GBPUSD',
        type: 'buy',
        entry: 1.26900,
        exit: 1.26800,
        sl: 1.26700,
        tp: 1.27300,
        lotSize: 0.4,
        riskPercent: 1.0,
        rrPlanned: 2.0,
        rrActual: -0.5,
        pipsProfit: -10,
        profit: -40,
        status: 'SL',
        assetCategory: 'Forex',
        notes: 'Third trade today. Getting chopped. Should stop trading.',
        emotionBefore: 'Tired',
        emotionAfter: 'Frustrated',
        mistakes: ['Overtrading'],
        strategy: 'Scalping',
        session: 'London',
        rulesUsed: []
    },
    {
        id: '19',
        date: '2024-02-20',
        time: '15:30',
        symbol: 'EURUSD',
        type: 'sell',
        entry: 1.08150,
        exit: 1.08100,
        sl: 1.08300,
        tp: 1.07800,
        lotSize: 0.5,
        riskPercent: 1.5,
        rrPlanned: 2.3,
        rrActual: 0.5,
        pipsProfit: -5,
        profit: -25,
        status: 'SL',
        assetCategory: 'Forex',
        notes: 'FOURTH trade! Overtrading badly. Revenge trading after the loss. Bad idea to continue.',
        emotionBefore: 'Revengeful',
        emotionAfter: 'Angry',
        mistakes: ['Overtrading', 'Revenge Trading', 'No Discipline'],
        strategy: 'Unspecified',
        session: 'New York',
        rulesUsed: []
    },
    {
        id: '20',
        date: '2024-02-20',
        time: '16:00',
        symbol: 'EURUSD',
        type: 'buy',
        entry: 1.08250,
        exit: 1.08200,
        sl: 1.08100,
        tp: 1.08600,
        lotSize: 0.6,
        riskPercent: 2.0,
        rrPlanned: 2.8,
        rrActual: -0.3,
        pipsProfit: -5,
        profit: -30,
        status: 'SL',
        assetCategory: 'Forex',
        notes: 'FIFTH trade! Increasing size to "make back" losses. MARTINGALE BEHAVIOR. Dangerous. STOP!',
        emotionBefore: 'Desperate',
        emotionAfter: 'Defeated',
        mistakes: ['Overtrading', 'Martingale', 'No SL Respect', 'Emotional'],
        strategy: 'Unspecified',
        session: 'New York',
        rulesUsed: []
    },
    
    // ========== WEEK 6: Break & Reset ==========
    {
        id: '21',
        date: '2024-02-22',
        time: '00:00',
        symbol: 'NONE',
        type: 'buy',
        entry: 0,
        exit: 0,
        sl: 0,
        tp: 0,
        profit: 0,
        status: 'open',
        notes: 'Took a day off. Reviewed my journal. Overtrading on Feb 20 cost me dearly. Need strict daily trade limit.',
        emotionBefore: 'Reflective',
        emotionAfter: 'Determined',
        mistakes: [],
        strategy: 'No Trade',
        session: 'Break',
    },
    
    // ========== WEEK 7: Back Stronger ==========
    {
        id: '22',
        date: '2024-02-26',
        time: '09:30',
        symbol: 'EURUSD',
        type: 'buy',
        entry: 1.08500,
        exit: 1.09200,
        sl: 1.08200,
        tp: 1.09500,
        lotSize: 0.5,
        riskPercent: 1.0,
        rrPlanned: 3.0,
        rrActual: 3.0,
        pipsProfit: 70,
        profit: 350,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Perfect comeback trade. Clean Silver Bullet. One and done for the day. Following my new rule: MAX 2 trades/day.',
        emotionBefore: 'Focused',
        emotionAfter: 'Proud',
        mistakes: [],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: ['Max 2 trades/day', '1:3 RR', 'FVG only']
    },
    {
        id: '23',
        date: '2024-02-27',
        time: '10:00',
        symbol: 'XAUUSD',
        type: 'sell',
        entry: 2030.00,
        exit: 2015.00,
        sl: 2040.00,
        tp: 2000.00,
        lotSize: 0.2,
        riskPercent: 1.2,
        rrPlanned: 2.5,
        rrActual: 2.5,
        pipsProfit: 150,
        profit: 300,
        status: 'TP',
        assetCategory: 'Commodities',
        notes: 'Strong supply zone rejection. Perfect risk management. Letting winners run. Discipline is improving!',
        emotionBefore: 'Patient',
        emotionAfter: 'Confident',
        mistakes: [],
        strategy: 'Supply & Demand',
        session: 'London',
        rulesUsed: ['Daily zone', 'Patience', 'Full TP']
    },
    {
        id: '24',
        date: '2024-02-28',
        time: '09:30',
        symbol: 'GBPUSD',
        type: 'buy',
        entry: 1.27000,
        exit: 1.26800,
        sl: 1.26700,
        tp: 1.27800,
        lotSize: 0.4,
        riskPercent: 1.0,
        rrPlanned: 3.0,
        rrActual: -0.5,
        pipsProfit: -20,
        profit: -80,
        status: 'SL',
        assetCategory: 'Forex',
        notes: 'Good setup but wrong this time. That\'s trading. Stopped for the day after 1 loss. NO REVENGE trading.',
        emotionBefore: 'Accepting',
        emotionAfter: 'Neutral',
        mistakes: [],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: ['Stop after loss', 'Accept losses']
    },
    
    // ========== WEEK 8: Consistency ==========
    {
        id: '25',
        date: '2024-03-01',
        time: '08:30',
        symbol: 'EURUSD',
        type: 'sell',
        entry: 1.08000,
        exit: 1.07600,
        sl: 1.08200,
        tp: 1.07200,
        lotSize: 0.5,
        riskPercent: 1.0,
        rrPlanned: 2.0,
        rrActual: 2.0,
        pipsProfit: 40,
        profit: 200,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Clean breakdown trade. Following process. Consistency is key.',
        emotionBefore: 'Disciplined',
        emotionAfter: 'Consistent',
        mistakes: [],
        strategy: 'London Breakout',
        session: 'London',
        rulesUsed: ['Trend following', 'Proper sizing']
    },
    {
        id: '26',
        date: '2024-03-04',
        time: '09:30',
        symbol: 'NAS100',
        type: 'buy',
        entry: 18000,
        exit: 18200,
        sl: 17900,
        tp: 18400,
        lotSize: 0.3,
        riskPercent: 1.0,
        rrPlanned: 2.0,
        rrActual: 2.0,
        pipsProfit: 200,
        profit: 600,
        status: 'TP',
        assetCategory: 'Indices',
        notes: 'Tech continues strong. Good demand zone entry. Patient for pullback.',
        emotionBefore: 'Patient',
        emotionAfter: 'Satisfied',
        mistakes: [],
        strategy: 'Supply & Demand',
        session: 'New York',
        rulesUsed: ['Wait for pullback', 'Demand zone']
    },
    {
        id: '27',
        date: '2024-03-05',
        time: '02:00',
        symbol: 'BTCUSD',
        type: 'sell',
        entry: 65000,
        exit: 63800,
        sl: 66000,
        tp: 62000,
        lotSize: 0.05,
        riskPercent: 1.5,
        rrPlanned: 2.3,
        rrActual: 2.4,
        pipsProfit: 1200,
        profit: 600,
        status: 'open',
        assetCategory: 'Crypto',
        notes: 'Crypto hitting resistance. Taking partials here. Still holding some for lower target.',
        emotionBefore: 'Confident',
        emotionAfter: 'Smart',
        mistakes: [],
        strategy: 'Crypto Swing',
        session: 'Asian',
        rulesUsed: ['Resistance rejection', 'Partial profits']
    },
    {
        id: '28',
        date: '2024-03-06',
        time: '10:30',
        symbol: 'XAUUSD',
        type: 'buy',
        entry: 2125.00,
        exit: 2145.00,
        sl: 2115.00,
        tp: 2160.00,
        lotSize: 0.3,
        riskPercent: 1.2,
        rrPlanned: 2.0,
        rrActual: 1.8,
        pipsProfit: 20,
        profit: 60,
        status: 'TP',
        assetCategory: 'Commodities',
        notes: 'Gold demand zone bounce. Not perfect but took what market gave.',
        emotionBefore: 'Realistic',
        emotionAfter: 'Content',
        mistakes: [],
        strategy: 'Supply & Demand',
        session: 'London',
        rulesUsed: ['Realistic targets']
    },
    {
        id: '29',
        date: '2024-03-07',
        time: '09:30',
        symbol: 'EURUSD',
        type: 'sell',
        entry: 1.09500,
        exit: 1.09000,
        sl: 1.09800,
        tp: 1.08500,
        lotSize: 0.5,
        riskPercent: 1.0,
        rrPlanned: 2.5,
        rrActual: 2.5,
        pipsProfit: 50,
        profit: 250,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'Strong reversal setup. Clean execution. Following my trading plan exactly.',
        emotionBefore: 'Disciplined',
        emotionAfter: 'Professional',
        mistakes: [],
        strategy: 'Silver Bullet',
        session: 'New York',
        rulesUsed: ['Plan execution', 'Perfect setup']
    },
    {
        id: '30',
        date: '2024-03-08',
        time: '08:00',
        symbol: 'GBPUSD',
        type: 'buy',
        entry: 1.28000,
        exit: 1.28500,
        sl: 1.27700,
        tp: 1.29200,
        lotSize: 0.4,
        riskPercent: 1.0,
        rrPlanned: 2.8,
        rrActual: 2.0,
        pipsProfit: 50,
        profit: 200,
        status: 'TP',
        assetCategory: 'Forex',
        notes: 'London breakout continuation. Strong momentum. Good week overall - 7 wins, 1 loss. Discipline paying off.',
        emotionBefore: 'Confident',
        emotionAfter: 'Accomplished',
        mistakes: [],
        strategy: 'London Breakout',
        session: 'London',
        rulesUsed: ['Momentum trading', 'Trend following']
    }
];

// ============================================
// SESSIONS WITH REALISTIC DATA
// ============================================

export const fakeSessions: Session[] = [
    {
        id: '1',
        name: 'London Session Focus',
        type: 'Forex Day Trading',
        date: '2024-02-05',
        timezone: 'GMT',
        strategyName: 'London Breakout',
        initialCapital: 5000
    },
    {
        id: '2',
        name: 'NY Silver Bullet Week',
        type: 'ICT Model Trading',
        date: '2024-02-12',
        timezone: 'EST',
        strategyName: 'Silver Bullet',
        initialCapital: 5000
    },
    {
        id: '3',
        name: 'Crypto & Gold Swing',
        type: 'Multi-Asset Swing',
        date: '2024-02-19',
        timezone: 'UTC',
        strategyName: 'Supply & Demand',
        initialCapital: 8000
    },
    {
        id: '4',
        name: 'Discipline Recovery',
        type: 'Psychology Focus',
        date: '2024-02-26',
        timezone: 'EST',
        strategyName: 'Silver Bullet',
        initialCapital: 5000
    },
    {
        id: '5',
        name: 'Consistency Challenge',
        type: 'Rule-Based Trading',
        date: '2024-03-01',
        timezone: 'EST',
        strategyName: 'Mixed',
        initialCapital: 6000
    }
];

// ============================================
// STRATEGIES WITH DETAILED RULES
// ============================================

export const fakeStrategies: Strategy[] = [
    {
        id: '1',
        name: 'Silver Bullet',
        description: 'ICT 9:30-10:30 NY Open Model. Trades fair value gaps at specific times.',
        status: 'Active',
        rules: [
            'Only trade 9:30-10:30 NY time',
            'Wait for 1min fair value gap',
            'Entry on 1min order block',
            'SL below/above previous structure',
            'Minimum 1:2.5 RR',
            'Max 2 trades per day',
            'No trading if Asian range < 30 pips'
        ]
    },
    {
        id: '2',
        name: 'London Breakout',
        description: 'Breakout of Asian range during London session with retest confirmation.',
        status: 'Active',
        rules: [
            'Identify Asian range (00:00-08:00 GMT)',
            'Wait for London open (08:00)',
            'Breakout + retest of Asian high/low',
            '5min candle confirmation',
            'SL on opposite side of range',
            'Target 1:2 minimum',
            'Avoid high impact news'
        ]
    },
    {
        id: '3',
        name: 'Supply & Demand',
        description: 'Trading institutional zones on higher timeframes. Patience required.',
        status: 'Active',
        rules: [
            'Mark daily/4H supply and demand',
            'Wait for price to reach zone',
            '15min confirmation candle',
            'Check higher timeframe trend',
            'Risk max 1.5% per trade',
            'Allow multiple tests of zone',
            'Scale out at 1:1, hold for 1:3'
        ]
    },
    {
        id: '4',
        name: 'Crypto Swing',
        description: 'Multi-day holds on crypto using support/resistance and market structure.',
        status: 'Testing',
        rules: [
            'Identify strong support/resistance',
            'Wait for 4H bullish/bearish structure',
            'RSI confirmation (not overbought/oversold)',
            'Position size 50% smaller due to volatility',
            'Use wider stops',
            'Take partials at 50% of move',
            'Hold core position for swing target'
        ]
    },
    {
        id: '5',
        name: 'Scalping',
        description: 'Quick 5-15 pip trades using moving averages and momentum.',
        status: 'Archived',
        rules: [
            'Only during high volatility',
            'EMA 9/21 crossover',
            'Max 3 trades per day',
            'Quick 5-10 pips',
            'Tight stops (5 pips)',
            'Stop if 2 consecutive losses'
        ]
    },
    {
        id: '6',
        name: 'EMA Crossover',
        description: 'Trend following using exponential moving average crosses.',
        status: 'Archived',
        rules: [
            'EMA 12/26 crossover',
            'Trade in direction of 200 EMA',
            'Volume confirmation',
            '1H timeframe minimum',
            'Avoid ranging markets'
        ]
    }
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export const calculateSeedStats = () => {
    const totalTrades = fakeTrades.length;
    const wins = fakeTrades.filter(t => t.profit > 0).length;
    const losses = fakeTrades.filter(t => t.profit < 0).length;
    const breakEven = fakeTrades.filter(t => t.profit === 0).length;
    
    const totalProfit = fakeTrades.reduce((sum, t) => sum + t.profit, 0);
    const winRate = (wins / (wins + losses)) * 100;
    
    const grossProfit = fakeTrades
        .filter(t => t.profit > 0)
        .reduce((sum, t) => sum + t.profit, 0);
    const grossLoss = Math.abs(fakeTrades
        .filter(t => t.profit < 0)
        .reduce((sum, t) => sum + t.profit, 0));
    const profitFactor = grossLoss === 0 ? grossProfit : grossProfit / grossLoss;
    
    const mistakes = fakeTrades.flatMap(t => t.mistakes || []);
    const mistakeCounts: Record<string, number> = {};
    mistakes.forEach(m => {
        mistakeCounts[m] = (mistakeCounts[m] || 0) + 1;
    });
    
    return {
        totalTrades,
        wins,
        losses,
        breakEven,
        winRate: winRate.toFixed(1),
        totalProfit: totalProfit.toFixed(2),
        profitFactor: profitFactor.toFixed(2),
        topMistakes: Object.entries(mistakeCounts)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5),
        avgProfitPerTrade: (totalProfit / totalTrades).toFixed(2)
    };
};

// Export summary for console logging
export const seedDataSummary = {
    trades: fakeTrades.length,
    sessions: fakeSessions.length,
    strategies: fakeStrategies.length,
    dateRange: `${fakeTrades[0].date} to ${fakeTrades[fakeTrades.length - 1].date}`,
    stats: calculateSeedStats()
};

export default {
    fakeTrades,
    fakeSessions,
    fakeStrategies,
    seedDataSummary
};
